name: CI

on:
    push:
        branches: [ develop ]

    pull_request:
        branches: [ develop ]
    
defaults:
    run:
        shell: bash
        working-directory: .

jobs:
    build:
        name: Generate APK
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Gradle cache
                uses: actions/cache@v2
                with:
                    path: |
                        ~/.gradle/caches
                        ~/.gradle/wrapper
                    key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
                    restore-keys: |
                        ${{ runner.os }}-gradle-
            -   name: set up JDK 17
                uses: actions/setup-java@v1
                with:
                    java-version: 17

            - name: Write compile time google-services.json file
              env:
                  GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
              run: echo $GOOGLE_SERVICES_JSON > app/google-services.json
                    
            - name: Touch local properties
              run: touch local.properties
                    
            - name: Access NAVER_CLIENT_ID
              env:
                  NAVER_CLIENT_ID: ${{ secrets.NAVER_CLIENT_ID }}
              run: echo "NAVER_CLIENT_ID = \"$NAVER_CLIENT_ID\"" >> local.properties
        
            - name: Access RUNNECT_BASE_URL
              env:
                  RUNNECT_BASE_URL: ${{ secrets.RUNNECT_BASE_URL }}
              run: echo "RUNNECT_BASE_URL=\"$RUNNECT_BASE_URL\"" >> local.properties

            - name: Access TMAP_BASE_URL
              env:
                  TMAP_BASE_URL: ${{ secrets.TMAP_BASE_URL }}
              run: echo "TMAP_BASE_URL=\"$TMAP_BASE_URL\"" >> local.properties
              
            - name: Access TMAP_API_KEY
              env:
                  TMAP_API_KEY: ${{ secrets.TMAP_API_KEY }}
              run: echo "TMAP_API_KEY=\"$TMAP_API_KEY\"" >> local.properties
              
            - name: Access GOOGLE_CLIENT_ID
              env:
                  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
              run: echo "GOOGLE_CLIENT_ID=\"$GOOGLE_CLIENT_ID\"" >> local.properties

            - name: Access REMOTE_KEY_APP_VERSION
              env:
                  REMOTE_KEY_APP_VERSION: ${{ secrets.REMOTE_KEY_APP_VERSION }}
              run: echo "REMOTE_KEY_APP_VERSION=\"$REMOTE_KEY_APP_VERSION\"" >> local.properties

            - name: Access KAKAO_CHANNEL_ID
              env:
                  KAKAO_CHANNEL_ID: ${{ secrets.KAKAO_CHANNEL_ID }}
              run: echo "KAKAO_CHANNEL_ID=\"$KAKAO_CHANNEL_ID\"" >> local.properties
              
            - name: Add kakao_strings.xml
              env:
                  KAKAO_NATIVE_APP_KEY: ${{ secrets.KAKAO_NATIVE_APP_KEY }}
                  KAKAO_REDIRECTION_SCHEME: ${{ secrets.KAKAO_REDIRECTION_SCHEME }}
              run: |
                  echo '<?xml version="1.0" encoding="utf-8"?>' > app/src/main/res/values/kakao_strings.xml
                  echo '<resources>' >> app/src/main/res/values/kakao_strings.xml
                  echo '    <string name="kakao_native_app_key">$KAKAO_NATIVE_APP_KEY</string>' >> app/src/main/res/values/kakao_strings.xml
                  echo '    <string name="kakao_redirection_scheme">$KAKAO_REDIRECTION_SCHEME</string>' >> app/src/main/res/values/kakao_strings.xml
                  echo '</resources>' >> app/src/main/res/values/kakao_strings.xml

            -   name: Change gradlew permissions
                run: chmod +x ./gradlew

            -   name: Build 
                run: ./gradlew assembleDebug --stacktrace
